#redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 5
        min-idle: 0